title: Financenerd 
description: Investing | Reaching financial independence | Lifehacks in Switzerland
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://financenerd.github.io/" # change this to the base hostname & protocol for your site


google_analytics:
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-154888004-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-154888004-1');
</script>


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: ""
image: /thumbnail-jumbo.png


plugins:
- jekyll-feed
  
gems:
- jekyll-seo-tag
  

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
